# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from enum import Enum

# Define a HAND with 21 landmarks


class LANDMARK(Enum):
    THUMB_FINGERTIP = "Thumb fingertip"
    INDEX_FINGER_FINGERTIP = "Index finger fingertip"
    MIDDLE_FINGER_FINGERTIP = "Middle finger fingertip"
    RING_FINGER_FINGERTIP = "Ring finger fingertip"
    PINKY_FINGER_FINGERTIP = "Pinky finger fingertip"
    WRIST_JOINT = "Wrist joint"
    THUMB_INTERMEDIATE_FRAME = "Thumb intermediate frame"
    THUMB_DISTAL_FRAME = "Thumb distal frame"
    INDEX_PROXIMAL_FRAME = "Index proximal frame"
    INDEX_INTERMEDIATE_FRAME = "Index intermediate frame"
    INDEX_DISTAL_FRAME = "Index distal frame"
    MIDDLE_PROXIMAL_FRAME = "Middle proximal frame"
    MIDDLE_INTERMEDIATE_FRAME = "Middle intermediate frame"
    MIDDLE_DISTAL_FRAME = "Middle distal frame"
    RING_PROXIMAL_FRAME = "Ring proximal frame"
    RING_INTERMEDIATE_FRAME = "Ring intermediate frame"
    RING_DISTAL_FRAME = "Ring distal frame"
    PINKY_PROXIMAL_FRAME = "Pinky proximal frame"
    PINKY_INTERMEDIATE_FRAME = "Pinky intermediate frame"
    PINKY_DISTAL_FRAME = "Pinky distal frame"
    PALM_CENTER = "Palm center"


LANDMARK_INDEX_TO_NAMING = [
    LANDMARK.THUMB_FINGERTIP,
    LANDMARK.INDEX_FINGER_FINGERTIP,
    LANDMARK.MIDDLE_FINGER_FINGERTIP,
    LANDMARK.RING_FINGER_FINGERTIP,
    LANDMARK.PINKY_FINGER_FINGERTIP,
    LANDMARK.WRIST_JOINT,
    LANDMARK.THUMB_INTERMEDIATE_FRAME,
    LANDMARK.THUMB_DISTAL_FRAME,
    LANDMARK.INDEX_PROXIMAL_FRAME,
    LANDMARK.INDEX_INTERMEDIATE_FRAME,
    LANDMARK.INDEX_DISTAL_FRAME,
    LANDMARK.MIDDLE_PROXIMAL_FRAME,
    LANDMARK.MIDDLE_INTERMEDIATE_FRAME,
    LANDMARK.MIDDLE_DISTAL_FRAME,
    LANDMARK.RING_PROXIMAL_FRAME,
    LANDMARK.RING_INTERMEDIATE_FRAME,
    LANDMARK.RING_DISTAL_FRAME,
    LANDMARK.PINKY_PROXIMAL_FRAME,
    LANDMARK.PINKY_INTERMEDIATE_FRAME,
    LANDMARK.PINKY_DISTAL_FRAME,
    LANDMARK.PALM_CENTER,
]

LANDMARK_NAMING_TO_INDEX = {k: i for i, k in enumerate(LANDMARK_INDEX_TO_NAMING)}

LANDMARK_CONNECTIVITY = [
    # pinky
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.WRIST_JOINT],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.PINKY_PROXIMAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.PINKY_PROXIMAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.PINKY_INTERMEDIATE_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.PINKY_INTERMEDIATE_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.PINKY_DISTAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.PINKY_DISTAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.PINKY_FINGER_FINGERTIP],
    ],
    # ring
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.WRIST_JOINT],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.RING_PROXIMAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.RING_PROXIMAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.RING_INTERMEDIATE_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.RING_INTERMEDIATE_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.RING_DISTAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.RING_DISTAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.RING_FINGER_FINGERTIP],
    ],
    # middle
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.WRIST_JOINT],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.MIDDLE_PROXIMAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.MIDDLE_PROXIMAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.MIDDLE_INTERMEDIATE_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.MIDDLE_INTERMEDIATE_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.MIDDLE_DISTAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.MIDDLE_DISTAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.MIDDLE_FINGER_FINGERTIP],
    ],
    # index
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.WRIST_JOINT],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.INDEX_PROXIMAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.INDEX_PROXIMAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.INDEX_INTERMEDIATE_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.INDEX_INTERMEDIATE_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.INDEX_DISTAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.INDEX_DISTAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.INDEX_FINGER_FINGERTIP],
    ],
    # thumb
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.WRIST_JOINT],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.THUMB_INTERMEDIATE_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.THUMB_INTERMEDIATE_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.THUMB_DISTAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.THUMB_DISTAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.THUMB_FINGERTIP],
    ],
    # palm
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.THUMB_INTERMEDIATE_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.INDEX_PROXIMAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.INDEX_PROXIMAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.MIDDLE_PROXIMAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.MIDDLE_PROXIMAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.RING_PROXIMAL_FRAME],
    ],
    [
        LANDMARK_NAMING_TO_INDEX[LANDMARK.RING_PROXIMAL_FRAME],
        LANDMARK_NAMING_TO_INDEX[LANDMARK.PINKY_PROXIMAL_FRAME],
    ],
]
