[project]
name = "hot3d"
version = "0.1.0"
description = "Add a short description here"
authors = ["Pierre Moulon <pierrem@meta.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]

setup = """
    python3 -m pip install 'git+https://github.com/facebookresearch/pytorch3d.git';
    """

viewer = "python3 viewer_mockup.py"

[dependencies]
python = "==3.10"
pip = "*"

[pypi-dependencies]
projectaria_tools = "*"
torch = "*"
vrs = "*"
matplotlib = "*"
