name: Setup and Test - Pixi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Hot3D on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14] # macos-14 is macSilicon
    steps:
      - name : Setup repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name : Setup pixi
        uses: prefix-dev/setup-pixi@v0.6.0
        with:
          pixi-version: v0.20.1
          cache: true

      - name: Python - Prepare environment
        shell: bash
        run: pixi run setup

      - name: Python - Unit test
        shell: pixi run bash {0}
        run: |
          export TEST_FOLDER="./data_loaders/tests/"
          python3 -m unittest data_loaders/tests/test_AriaDataProvider.py
          python3 -m unittest data_loaders/tests/test_HandBox2dDataProvider.py
          python3 -m unittest data_loaders/tests/test_ObjectBox2dDataProvider.py

      - name : Python - Test dataset viewer
        shell: pixi run bash {0}
        run: |
          rerun analytics disable
          # TODO add viewer running functional test
